Items:
  # Format:
  # '(timer)': "(format)"
  # Available placeholders:
  # {time} - time remaining before remove (in seconds)
  # {display_name} - display name of itemstack (if empty - used localized material name}
  # {amount} - itemstack amount
  Display-name-format: 
    '1': "§c⚠ {time} §7| §f{display_name} §a{amount}x"
    '10': "§c{time}"
  Remove-timer:
    # Timer for removing an item in seconds
    Default: 30
    After-player-death: 180
    Async: true
    # Section for specifying a unique timer or display name
    # for certain materials
    # Format:
    # <material name>:
    #   <timer>: 15
    #   <display name>: "Test"
    # If you only need to edit one parameter
    # (name or time) you can just delete the line with the second.
    Custom-materials:
      COBBLESTONE:
        Timer: 15
        Display-name: "Cobblestone :D"
      STONE:
        Timer: 10
      GRASS:
        Display-name: "Grazz"
      SAND:
        Timer: 0
        

      
   
# Worlds in which plugin does not work
Restricted-worlds:
- restricted_world
