name: XItemsRemover
main: ru.xezard.items.remover.ItemsRemoverPlugin
description: Removes dropped items with a timer displayed on them!
author: Xezard
website: http://xezard.ru
version: 1.0.8

commands:
  itemsremover:
    aliases: [ir]
    description: Main command